const DESKTOP_SCREEN_WIDTH = 1280;
const TABLET_SCREEN_WIDTH = 1024;
const MOBILE_SCREEN_WIDTH = 768;

const DESKTOP_ADDED_CARD_ROW = 4;
const DESKTOP_TABLET_ADDED_CARD_ROW = 3;
const TABLET_MOBILE_ADDED_CARD_ROW = 2;
const MOBILE_ADDED_CARD_ROW = 1;

const FROM_FIRST_CARD = 0;

const TO_DESKTOP_INITIAL_NUMBER_CARDS = 16;
const TO_DESKTOP_TABLET_INITIAL_NUMBER_CARDS = 12;
const TO_TABLET_MOBILE_INITIAL_NUMBER_CARDS = 8;
const TO_MOBILE_INITIAL_NUMBER_CARDS = 5;

const TIME_DELAY_MS = 150;

export {
  DESKTOP_SCREEN_WIDTH,
  TABLET_SCREEN_WIDTH,
  MOBILE_SCREEN_WIDTH,
  DESKTOP_ADDED_CARD_ROW,
  DESKTOP_TABLET_ADDED_CARD_ROW,
  TABLET_MOBILE_ADDED_CARD_ROW,
  MOBILE_ADDED_CARD_ROW,
  FROM_FIRST_CARD,
  TO_DESKTOP_INITIAL_NUMBER_CARDS,
  TO_DESKTOP_TABLET_INITIAL_NUMBER_CARDS,
  TO_TABLET_MOBILE_INITIAL_NUMBER_CARDS,
  TO_MOBILE_INITIAL_NUMBER_CARDS,
  TIME_DELAY_MS,
};
